name: Quality
on: push
jobs:
    cs-fixer:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Cs-Fixer
                run: |
                    wget -q https://cs.symfony.com/download/php-cs-fixer-v2.phar -O php-cs-fixer
                    chmod a+x php-cs-fixer
                    PHP_CS_FIXER_IGNORE_ENV=true ./php-cs-fixer fix src --dry-run

    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                phpstan-level: [ 3, 5, 7, 8 ]
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/cache@v2
                with:
                    path: '**/vendor'
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-composer-
            -   uses: php-actions/composer@v5
                with:
                    args: --prefer-dist
                    php_version: 8.0

            -   name: PHPStan
                uses: php-actions/phpstan@v2
                with:
                    path: src/
                    args: --level=${{ matrix.phpstan-level }}

